kind: Deployment
apiVersion: apps/v1
metadata:
  name: bang
  labels:
    app: bang
  namespace: bang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bang
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bang
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Amsterdam
          image: marklagendijk/toogoodtogo-watcher
          name: bang
          volumeMounts:
            - name: task-pv-storage
              mountPath: /home/node/.config/toogoodtogo-watcher-nodejs
      restartPolicy: Always
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: pvc

