apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: bang
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
